# Generated by Django 3.0.6 on 2020-05-24 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50)),
                ('date', models.DateField()),
                ('intime', models.TimeField()),
                ('outtime', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=60, unique=True)),
                ('employeeid', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=150)),
                ('ename', models.CharField(max_length=30)),
                ('age', models.PositiveIntegerField(null=True)),
                ('mobileno', models.CharField(max_length=10)),
                ('entry', models.TextField(null=True)),
                ('date joined', models.DateTimeField(auto_now_add=True)),
                ('last login', models.DateTimeField(auto_now=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
